<pre rel="html" class="snippet language-html"><code>&lt;div class="grid-outer"&gt;
	&lt;div class="grid-row"&gt;
		&lt;div class="grid-col-4 col-single"&gt;
			&lt;div class="inner"&gt;
				&lt;p&gt;single child&lt;/p&gt;
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;div class="grid-col-8 col-group"&gt;
			&lt;div class="grid-col-4"&gt;
				&lt;div class="inner"&gt;
					&lt;p&gt;group child&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
			&lt;div class="grid-col-4"&gt;
				&lt;div class="inner"&gt;
					&lt;p&gt;group child&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
			&lt;div class="grid-col-4"&gt;
				&lt;div class="inner"&gt;
					&lt;p&gt;group child&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/div&gt;
</code></pre>