<pre rel="html" class="snippet language-html"><code>&lt;div class="i-outer"&gt;
	&lt;div class="i-row"&gt;
		&lt;div class="i-col-12 i-col-xs-4"&gt;
			&lt;div class="inner"&gt;
				&lt;p&gt;single child&lt;/p&gt;
			&lt;/div&gt;
		&lt;/div&gt;
		&lt;div class="i-col-12 i-col-xs-8 col-group"&gt;
			&lt;div class="i-col-4"&gt;
				&lt;div class="inner"&gt;
					&lt;p&gt;group child&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
			&lt;div class="i-col-4"&gt;
				&lt;div class="inner"&gt;
					&lt;p&gt;group child&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
			&lt;div class="i-col-4"&gt;
				&lt;div class="inner"&gt;
					&lt;p&gt;group child&lt;/p&gt;
				&lt;/div&gt;
			&lt;/div&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/div&gt;
</code></pre>